prawdziwe = [
Movie(title = 'Tie Me Up! Tie Me Down!', release = 1990, genre = 'Comedy'),
Movie(title = 'High Heels', release = 1991, genre = 'Comedy'),
Movie(title = 'Dead Zone  The', release = 1983, genre = 'Horror'),
Movie(title = 'Cuba', release = 1979, genre = 'Action'),
Movie(title = 'Days of Heaven', release = 1978, genre = 'Drama' ),
Movie(title = 'Octopussy', release = 1983, genre = 'Action' ),
Movie(title = 'Target Eagle', release = 1984, genre = 'Action' ),
Movie(title = 'American Angels: Baptism of Blood  The', release = 1989, genre = 'Drama' ),
Movie(title = 'Subway', release = 1985, genre = 'Drama' ),
Movie(title = 'Camille Claudel', release = 1990, genre = 'Drama' ),
Movie(title = 'Fanny and Alexander', release = 1982, genre = 'Drama' ),
Movie(title = 'Tragedy of a Ridiculous Man', release = 1982, genre = 'Drama' ),
Movie(title = 'A Man & a Woman', release = 1966, genre = 'Drama' ),
Movie(title = 'A Man & a Woman: Twenty releases Later', release = 1986, genre = 'Drama' ),
Movie(title = 'Blackmail', release = 1929, genre = 'Mystery' ),
Movie(title = 'Donovan s Reef', release = 1963, genre = 'Comedy' ),
Movie(title = 'Tucker: The Man & His Dream', release = 1988, genre = 'Drama' ),
Movie(title = 'Scrooged', release = 1988, genre = 'Comedy' ),
Movie(title = 'Running Man  The', release = 1987, genre = 'Science Fiction' ),
Movie(title = 'Raiders of the Lost Ark', release = 1981, genre = 'Action' ),
Movie(title = 'Predator 2', release = 1991, genre = 'Action' ),
Movie(title = 'Colors', release = 1988, genre = 'Drama' ),
Movie(title = 'Un Hombre y una Mujer', release = 1966, genre = 'Drama' ),
Movie(title = 'Official Story  The', release = 1985, genre = 'Drama' ),
Series(title = 'Gra o Tron', release = 2012, genre = 'Fantasy',season = 'S01', episode = 'E02' ),
Series(title = 'Gra o Tron', release = 2012, genre = 'Fantasy',season = 'S01', episode = 'E03' ),
Series(title = 'Gra o Tron', release = 2012, genre = 'Fantasy',season = 'S02', episode = 'E01' ),
Series(title = 'Gra o Tron', release = 2012, genre = 'Fantasy',season = 'S02', episode = 'E02' ),
Series(title = 'Gra o Tron', release = 2012, genre = 'Fantasy',season = 'S02', episode = 'E03' ),
Series(title = 'Gra o Tron', release = 2012, genre = 'Fantasy',season = 'S03', episode = 'E01' ),
Series(title = 'Gra o Tron', release = 2012, genre = 'Fantasy',season = 'S03', episode = 'E02' ),
Series(title = 'Gra o Tron', release = 2012, genre = 'Fantasy',season = 'S03', episode = 'E03' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S01', episode = 'E01' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S01', episode = 'E02' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S01', episode = 'E03' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S02', episode = 'E01' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S02', episode = 'E02' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S02', episode = 'E03' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S03', episode = 'E01' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S03', episode = 'E02' ),
Series(title = 'Rodzina Soprano', release = 2000, genre = 'Drama',season = 'S03', episode = 'E03' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S01', episode = 'E01' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S01', episode = 'E02' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S01', episode = 'E03' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S02', episode = 'E01' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S02', episode = 'E02' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S02', episode = 'E03' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S03', episode = 'E01' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S03', episode = 'E02' ),
Series(title = 'The Office', release = 2010, genre = 'Comedy',season = 'S03', episode = 'E03' ),
]